Update java-maven-api-develop.yml

diff --git a/.github/workflows/java-maven-api-develop.yml b/.github/workflows/java-maven-api-develop.yml
--- a/.github/workflows/java-maven-api-develop.yml
+++ b/.github/workflows/java-maven-api-develop.yml
@@ -48,3 +48,27 @@ jobs:
         mkdir -p ~/.m2
         echo "<settings><servers><server><id>github</id><username>govindarajanv</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
         mvn deploy
+  integration-test:
+    name: Contract Testing
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v1
+    - name: Set up JDK 1.11
+      uses: actions/setup-java@v1
+      with:
+        java-version: 1.11
+    - name: API Contract Testing
+      run: |
+        #VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:execxml)
+        VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
+        java -jar target/calculator-api-$VERSION.jar &
+        PID=$!
+        sleep 20
+        result=$(curl -s http://localhost:8080/addition/1/2/3 | jq .result)
+        if [ $result -eq 6 ]; then
+          echo "API Contract Testing is successful"
+        else
+          echo "API Contract Testing failed"
+          exit 1
+        fi
+        kill -9 $PID > /dev/null
