Update java-maven-api-quick-poc.yml

diff --git a/.github/workflows/java-maven-api-quick-poc.yml b/.github/workflows/java-maven-api-quick-poc.yml
--- a/.github/workflows/java-maven-api-quick-poc.yml
+++ b/.github/workflows/java-maven-api-quick-poc.yml
@@ -36,3 +36,25 @@ jobs:
           docker images
           docker push govindarajanv/calculator-api:$VERSION 
           docker push govindarajanv/calculator-api:latest
+  deploy:
+    name: Depploy/Release to production
+    runs-on: ubuntu-latest
+    steps:
+    - name: Deploy to Heroku
+      run: |
+        sudo apt-get install libxml2-utils
+        VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)      
+        mvn clean install
+        docker build -t registry.heroku.com/calculator-java-maven-service/web:$VERSION --build-arg value=$VERSION . 
+        docker push registry.heroku.com/calculator-java-maven-service/web:$VERSION
+        docker build -t registry.heroku.com/calculator-java-maven-service/web:latest --build-arg value=$VERSION .
+        docker push registry.heroku.com/calculator-java-maven-service/web:latest
+        heroku container:rm web -a calculator-java-maven-service
+        heroku container:release web -a calculator-java-maven-service
+        result=$(curl -s https://calculator-java-maven-service.herokuapp.com/addition/1/2/3 | jq .result)
+        if [ $result -eq 6 ]; then
+          echo "Application is successfully deployed in production"
+        else
+          echo "Prod deployment failed"
+          exit 1
+        fi    
